import type { Metadata } from "next";
import { Inter, Source_Code_Pro } from "next/font/google";
import { RootProvider } from "./rootProvider";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const sourceCodePro = Source_Code_Pro({
  variable: "--font-source-code-pro",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_PROJECT_NAME,
  description:
    "Generated by `create-onchain`, a Next.js template for OnchainKit",
  other: {
    'fc:frame': JSON.stringify({
      version: 'next',
      imageUrl: 'https://basey-bird-inl8.vercel.app/opengraph-image',
      button: {
        title: 'Play Basey Bird',
        action: {
          type: 'launch_frame',
          name: 'Basey Bird',
          url: 'https://basey-bird-inl8.vercel.app',
          splashImageUrl: 'https://basey-bird-inl8.vercel.app/icon.png',
          splashBackgroundColor: '#0052FF'
        }
      }
    })
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${sourceCodePro.variable}`}>
        <RootProvider>{children}</RootProvider>
      </body>
    </html>
  );
}
